name: CI

on:
  pull_request: ~
  push:
    branches:
      - master
  schedule:
    - cron: "47 6 * * 1" # once a month, to surface issues with newer dependencies

jobs:
  Tests:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        dependencies: ["highest"]
        include:
          - description: "(lowest)"
            php: "8.1"
            dependencies: "lowest"

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - name: "Install dependencies"
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: "Run PHPStan analysis"
        run: composer phpstan
      - name: "Run tests"
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always
      - name: "Upload test coverage"
        uses: codecov/codecov-action@v5
        with:
          files: "./coverage.xml"
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
